steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - --file
      - Dockerfile.cloud-runtime
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: us-docker.pkg.dev/example-project/inkbridge/runtime:replace-me
