import assert from 'node:assert/strict';
import {execFile} from 'node:child_process';
import {mkdtemp, readFile, rm, writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {dirname, join} from 'node:path';
import test from 'node:test';
import {fileURLToPath} from 'node:url';
import {promisify} from 'node:util';

const execFileAsync = promisify(execFile);
const root = dirname(dirname(fileURLToPath(import.meta.url)));

test('embedded manifest export is not swallowed by its generated comment', async () => {
  const work = await mkdtemp(join(tmpdir(), 'inkbridge-manifest-'));
  try {
    const input = join(work, 'manifest.json');
    const output = join(work, 'generatedManifest.js');
    await writeFile(
      input,
      JSON.stringify({
        schemaVersion: 1,
        manifestId: 'manifest-test',
        operations: [],
      }),
      'utf8',
    );
    await execFileAsync(process.execPath, [
      join(root, 'embed-manifest.mjs'),
      input,
      output,
    ]);
    const javascript = await readFile(output, 'utf8');
    assert.match(
      javascript,
      /^\/\/ Generated by[^\r\n]*\r?\nexport const EMBEDDED_MANIFEST = /,
    );
    assert.match(javascript, /"manifestId":"manifest-test"/);
  } finally {
    await rm(work, {recursive: true, force: true});
  }
});
